[pytest]
pythonpath = .
addopts = --cov=auth --cov=cache --cov=crud --cov=database --cov=email_service --cov=main --cov=models --cov=rate_limiter --cov=schemas --cov-report=term-missing --cov-fail-under=75
asyncio_mode = auto
